title: Sparsh Palkhiwala
logo: sparsh_img.jpg
description: I am a versatile software developer and data scientist with expertise in a wide range of programming languages, tools, and frameworks. With a passion for innovation and problem-solving, I thrive in dynamic environments where I can leverage my skills to create impactful solutions. From developing efficient algorithms to building intuitive user interfaces, I am committed to delivering high-quality results that drive technological advancement and solve real-world challenges.
#show_downloads: true
theme: jekyll-theme-minimal
linkedin: https://www.linkedin.com/in/sparsh-palkhiwala/
email: spalkhiw@asu.edu
